version: "2"
services:
    web:
        build:
            context: ../
            dockerfile: docker/Dockerfile
        image: angular2-reactive
        ports:
            # - "3000:3000"
            - "9876:9876"
            - "9000:9000"
            # - "49153:49153"

        volumes:
            # Remaps the volume for live editing
            - ../:/workspace

        # command: npm install @ngrx/effects @ngrx/router-store @ngrx/store @ngrx/core --save-dev
        command: ng serve --host 0.0.0.0 --port 9000
        # command: ng test --host 0.0.0.0 --port 9876
        # npm start

        environment:
            # ng build --env=stag
            BUILD_ENVIRONMENT: ""
